name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          # This caches Gradle dependencies and build outputs.
          # No specific permissions are usually needed here beyond default.
          # The setup-gradle action manages the Gradle wrapper and executable permissions.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }} # Cache is read-only for non-main branches or PRs.

      - name: Assemble Debug Build
        run: ./gradlew assembleDebug