name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          # Validate Gradle wrapper checksums to ensure integrity and re-download if corrupted.
          # This helps prevent issues where the wrapper JAR might be missing or damaged,
          # which can lead to "Could not find or load main class" errors.
          validate-wrappers: true

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Assemble Debug Build
        # Running ./gradlew directly is sufficient and idiomatic, removing the 'bash' prefix.
        run: ./gradlew assembleDebug